'use client';
import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillGithub, AiFillLinkedin, AiFillInstagram } from 'react-icons/ai';
import Image from 'next/image';
import deved from '../../public/Layer.png';
import bangkit from '../../public/bangkit.jpg';
import web1 from '../../public/MyKIP.png';
import TypeEffect from './TypeEffects';
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Nabil Azizi Portfolio</title>
        <meta name="description" content="Generated by create" />
        <link rel="icon" href="./favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="text-xl">My Portfolio.</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8" href="#">
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="flex flex-col">
            <div className="text-center p-10 py-10">
              <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:text-teal-400">Muhammad Nabil Azizi</h2>
              <div className="text-2xl py-2 dark:text-white">{TypeEffect()}</div>

              <p className=" dark:text-gray-200 text-md py-5 leading-8 text-gray-800 text-justify">
                Undergraduate Data Science student at Institut Teknologi Sumatera with a focus on studying data science, data analysis, and artificial intelligence. I have a strong passion for leveraging data-driven insights to solve
                complex problems. In addition to my academic pursuits, I am also deeply interested in web development, encompassing both the back-end and front-end aspects. I enjoy creating dynamic and user-friendly websites that provide
                seamless experiences for users. My goal is to combine my data science skills with web development to build interactive and data-driven applications.
              </p>
            </div>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://github.com/NabilAzizii" target="_blank">
                <AiFillGithub />
              </a>
              <a href="https://www.linkedin.com/in/nabilazizi/" target="_blank">
                <AiFillLinkedin />
              </a>
              <a href="https://www.instagram.com/nabilazizz/" target="_blank">
                <AiFillInstagram />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-800 to-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96 hover:scale-105 transition-all duration-200">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        {/*  */}
        <section>
          <div>
            <h3 className="text-3xl pt-8 pb- dark:text-white">Experiences</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white text-justify">
              Since the beginning of my journey as a <span className="text-teal-500">data science student</span> and <span className="text-teal-500">self-taught web developer</span>, I've done with any
              <span className="text-teal-500"> experiences </span>
              Through personal projects, I honed my analytical skills, extracting insights from complex data. Freelance web development projects allowed me to create functional websites that aligned with client needs. As a self-taught
              person, I invested time in learning new technologies, exploring frameworks, and perfecting <span className="text-teal-500"> front-end and back-end development </span>. Problem-solving and adaptability are my strengths, helping
              me to take on independent challenges. Overall, my diverse experience in data science and web development provides a strong foundation. I am eager to contribute, collaborate, and continue my growth in this field.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 flex-1 dark:bg-white">
              <div className="flex justify-center items-center ">
                <Image src={bangkit} width={400} height={300} className="rounded-xl hover:shadow-md hover:scale-105 transition-all duration-200" />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2">Cloud Computing Cohort</h3>
              <ul className="py-2 text-justify">
                <li className="py-2 ">Learn and practice the use of various leading cloud platforms, such as Google Cloud Platform</li>
                <li className="py-2">Confronting a technical challenge in the development of a cloud-based application or system and successfully overcoming the problem by using the knowledge and skills acquired.</li>
                <li className="py-2">Participated in a capstone project with team members. In this project, I handled the Back-end part for an Application where I created and handled the API creation for my team's Project Application.</li>
              </ul>
              <h4 className="py-4 text-teal-600">What I've Learned</h4>
              <p className="text-gray-800 py-1 font-bold">Google Cloud Platforms</p>
              <p className="text-gray-800 py-1 font-bold">Back-end Developer</p>
              <p className="text-gray-800 py-1 font-bold">Teamwork</p>
            </div>
          </div>
        </section>
        {/*  */}
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Projects</h3>
          </div>
          <div className="lg:flex gap-10 ">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 flex-1 dark:bg-white">
              <div className="flex justify-center items-center ">
                <Image src={web1} width={400} height={300} className="rounded-xl hover:shadow-md hover:scale-105 transition-all duration-200" />
              </div>
              <h3 className="text-lg font-medium pt-8 pb-2">MyKIP</h3>
              <p className="text-md py-2 leading-8 text-gray-800 text-justify">
                Project MyKIP is aimed at assisting high school graduates who are interested in applying for the KIP (Kartu Indonesia Pintar) scholarship program or individuals responsible for managing the KIP program. The project focuses
                on creating a platform that ensures the effective and targeted distribution of the KIP scholarships.
              </p>
              <p className="py-2">
                Create API/Backend for Application. <br />
                Monitoring Cloud services on Google Cloud Platform.
                <br /> Creating Machine Learning API for Application.
              </p>
              <h4 className="pt-4 text-teal-600">Tools I've Use</h4>
              <p className="text-gray-800 py-1 font-bold">Google Cloud Platforms</p>
              <p className="text-gray-800 py-1 font-bold">Node Js</p>
              <p className="text-gray-800 py-1 font-bold">Flask Python</p>
              <div className="py-4 hover:scale-105 transition-all duration-200">
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white border-none rounded-md px-4 py-2 font-bold hover:shadow-md transition-all duration-200"
                  href="https://github.com/yunama47/CapstoneTeamC23-PC621"
                  target="_blank"
                >
                  Go to Code
                </a>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
