'use client';
import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillGithub, AiFillLinkedin, AiFillInstagram } from 'react-icons/ai';
import Image from 'next/image';
import deved from '../../public/Layer.png';
import bangkit from '../../public/bangkit.jpg';
import mykip from '../../public/MyKIP.png';
import jobless from '../../public/jobless.png';
import space from '../../public/space.png';
import TypeEffect from './TypeEffects';
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>Nabil Azizi Portfolio</title>
        <meta name="description" content="Generated by create" />
        <link rel="icon" href="./favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-[#242629]">
        <section className="min-h-screen max-w-screen-xl mx-auto">
          <nav className="bg-white dark:bg-[#242629] fixed w-full z-20 top-0 left-0 border-b border-gray-200 dark:border-gray-600 dark:text-white">
            <div className="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
              <h1 className="text-xl">My Portfolio.</h1>
              <ul className="flex items-center">
                <li>
                  <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl" />
                </li>
                <li>
                  <a
                    className="bg-gradient-to-tl from-[#4334cf] dark:from-[#0083B0] dark:to-[#00B4DB] to-[#c9f28a] text-white px-4 py-2 border-none rounded-md ml-8"
                    href="https://drive.google.com/file/d/1juzlyXhyuB6lM5yhGWJBhbMbBjz5a-7h/view?usp=sharing"
                  >
                    Resume
                  </a>
                </li>
              </ul>
            </div>
          </nav>

          <div className="py-24 flex flex-col">
            <div className="text-center">
              <h2 className="text-5xl py-2 text-[#4334cf] font-medium md:text-6xl dark:text-[#00B4DB]">Muhammad Nabil Azizi</h2>
              <div className="text-2xl py-2 dark:text-white">{TypeEffect()}</div>
              <div className=" dark:text-gray-200 text-md py-5 leading-8 text-gray-800 text-justify">
                <p>
                  As an undergraduate <span className="font-medium text-[#4334cf] dark:text-[#00B4DB]">Data Science student</span> at Institut Teknologi Sumatera, my primary focus is on studying
                  <span className="font-medium text-[#4334cf] dark:text-[#00B4DB]"> data science, data analysis, and artificial intelligence.</span> I am deeply passionate about leveraging data-driven insights to solve complex problems.
                </p>
                <p className="py-4">
                  Additionally, I have a strong <span className="font-medium dark:text-[#00B4DB] text-[#4334cf]">interest in web development</span>, encompassing both{' '}
                  <span className="font-medium dark:text-[#00B4DB] text-[#4334cf]">back-end and front-end</span> aspects. I thoroughly enjoy creating dynamic and user-friendly websites that deliver seamless experiences for users.
                </p>
                <p>
                  My <span className="font-medium dark:text-[#00B4DB] text-[#4334cf]">goals</span> is to combine my skills in data science with web development to{' '}
                  <span className="dark:text-[#00B4DB] font-medium text-[#4334cf]">build interactive and data-driven applications.</span>
                </p>
              </div>
            </div>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://github.com/NabilAzizii" target="_blank">
                <AiFillGithub />
              </a>
              <a href="https://www.linkedin.com/in/nabilazizi/" target="_blank">
                <AiFillLinkedin />
              </a>
              <a href="https://www.instagram.com/nabilazizz/" target="_blank">
                <AiFillInstagram />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-[#4334cf] to-[#c9f28a] dark:from-[#0083B0] dark:to-transparent rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96 md:hover:scale-120 transition-all duration-200 hover:scale-110">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>

          {/*  */}

          <div>
            <h3 className="text-3xl pt-8 pb-2 dark:text-white">Experiences</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white text-justify">
              Since the beginning of my journey as a <span className="dark:text-[#00B4DB] font-medium text-[#4334cf]">data science student</span> and{' '}
              <span className="text-[#4334cf] dark:text-[#00B4DB] font-medium">self-taught web developer</span>, I've done with any
              <span className="text-[#4334cf] dark:text-[#00B4DB] font-medium"> experiences </span>
              Through personal projects, I honed my analytical skills, extracting insights from complex data. Freelance web development projects allowed me to create functional websites that aligned with client needs. As a self-taught
              person, I invested time in learning new technologies, exploring frameworks, and perfecting <span className="dark:text-[#00B4DB] text-[#4334cf] font-medium"> front-end and back-end development.</span>{' '}
              <span className="text-[#4334cf] dark:text-[#00B4DB] font-medium">Problem-solving and adaptability are my strengths</span>, helping me to take on independent challenges. Overall, my diverse experience in data science and web
              development provides a strong foundation. I am eager to contribute, collaborate, and continue my growth in this field.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg py-10 lg:px-24 px-5 rounded-xl my-10 flex-1 dark:bg-[#16161a] dark:text-white">
              <div className="flex justify-center items-center ">
                <a href="https://grow.google/intl/id_id/bangkit/?tab=machine-learning" target="_blank">
                  <Image src={bangkit} width={400} height={300} className="rounded-xl hover:shadow-md hover:scale-105 transition-all duration-200" />
                </a>
              </div>
              <h3 className="text-lg font-bold pt-8 pb-2">Bangkit Academy 2023 By Google, GoTo, Traveloka</h3>
              <h3 className="text-lg font-medium pt-4 pb-2">Cloud Computing Cohort</h3>
              <ul className="py-2 text-justify">
                <li className="py-2">Learn and practice the use of various leading cloud platforms, such as Google Cloud Platform</li>
                <li className="py-2">Confronting a technical challenge in the development of a cloud-based application or system and successfully overcoming the problem by using the knowledge and skills acquired.</li>
                <li className="py-2">Participated in a capstone project with team members. In this project, I handled the Back-end part for an Application where I created and handled the API creation for my team's Project Application.</li>
              </ul>
              <h4 className="py-4 text-[#4334cf] dark:text-[#00B4DB]">What I've Learned</h4>
              <p className="text-gray-800 dark:text-[#94a1b2] py-1 font-bold">Google Cloud Platforms</p>
              <p className="text-gray-800 dark:text-[#94a1b2] py-1 font-bold">Back-end Developer</p>
              <p className="text-gray-800 dark:text-[#94a1b2] py-1 font-bold">Teamwork</p>
              <div className="max-w-screen-sm mx-auto">
                <div>
                  <h3 className="text-3xl pt-8">Project on Bangkit</h3>
                  <hr className="border-gray-300 mt-1" />
                </div>
                <div className="lg:flex gap-10">
                  <div className="text-center lg:shadow-lg py-5 px-5 rounded-xl my-10 flex-1 dark:bg-[#242629]">
                    <div className="flex justify-center items-center ">
                      <Image src={mykip} width={400} height={300} className="rounded-xl hover:shadow-md hover:scale-105 transition-all duration-200" />
                    </div>
                    <h3 className="text-lg font-medium pt-8 pb-2 dark:text-[#fffffe]">MyKIP</h3>
                    <p className="text-md py-2 leading-8 dark:text-[#94a1b2] text-justify">
                      Project MyKIP is aimed at assisting high school graduates who are interested in applying for the KIP (Kartu Indonesia Pintar) scholarship program or individuals responsible for managing the KIP program. The project
                      focuses on creating a platform that ensures the effective and targeted distribution of the KIP scholarships.
                    </p>
                    <p className="py-2">
                      Create API/Backend for Application. <br />
                      Monitoring Cloud services on Google Cloud Platform.
                      <br /> Creating Machine Learning API for Application.
                    </p>
                    <h4 className="pt-4 text-[#4334cf] dark:text-[#00B4DB]">Tools I've Use</h4>
                    <p className="text-gray-800 dark:text-[#94a1b2] py-1 font-bold">Google Cloud Platforms</p>
                    <p className="text-gray-800 dark:text-[#94a1b2] py-1 font-bold">Node Js</p>
                    <p className="text-gray-800 dark:text-[#94a1b2] py-1 font-bold">Flask Python</p>
                    <div className="py-4 hover:scale-105 transition-all duration-200">
                      <a
                        className="bg-gradient-to-tl from-[#4334cf] to-[#c9f28a] dark:from-[#0083B0] dark:to-[#00B4DB] text-white border-none rounded-md px-4 py-2 font-medium hover:shadow-md transition-all duration-200"
                        href="https://github.com/yunama47/CapstoneTeamC23-PC621"
                        target="_blank"
                      >
                        Code
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div>
            <h3 className="text-3xl pt-8 pb-2 dark:text-white">Projects</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-white text-justify">
              As a <span className="text-[#4334cf] dark:text-[#00B4DB] font-medium"> Jr.Web Developer </span>(Front-end and Back-end), during these projects, I always strive to continuously improve my expertise in the latest technologies
              and web development best practices. I also actively share my knowledge, and seek feedback to continuously improve the quality of the products we produce.
            </p>
          </div>
          <div className="lg:flex justify-center gap-10">
            <div className="text-center shadow-lg py-5 lg:max-w-[50%] px-5 rounded-xl my-10 flex-1 dark:bg-[#16161a]">
              <div className="flex justify-center items-center ">
                <Image src={jobless} width={400} height={300} className="rounded-xl hover:shadow-md hover:scale-105 transition-all duration-200" />
              </div>
              <h3 className="text-lg  font-medium pt-8 pb-2 text-[#4334cf] dark:text-[#00B4DB]">Landing Page (Desktop Only)</h3>
              <p className="lg:text-base text-xs py-2 leading-8 text-gray-800 dark:text-[#94a1b2] italic ">*Doesn't work on devices other than desktop</p>
              <h4 className="pt-4 text-[#4334cf] dark:text-[#00B4DB]">Tools I've Use</h4>
              <p className="text-gray-800 dark:text-[#94a1b2] py-1 font-bold">HTML</p>
              <p className="text-gray-800 dark:text-[#94a1b2] py-1 font-bold">CSS</p>
              <p className="text-gray-800 dark:text-[#94a1b2] py-1 font-bold">Figma</p>
              <div className="flex justify-center items-center  gap-8">
                <div className="py-5 hover:scale-105 transition-all duration-200">
                  <a
                    className="bg-gradient-to-tl from-[#4334cf] to-[#c9f28a] dark:from-[#0083B0] dark:to-[#00B4DB] text-white border-none rounded-md px-4 py-2 font-medium hover:shadow-md transition-all duration-200"
                    href="https://github.com/NabilAzizii/Latihan-Frontend/tree/landing-page-jobless"
                    target="_blank"
                  >
                    Code
                  </a>
                </div>
                <div className="py-4 hover:scale-105 transition-all duration-200">
                  <a
                    className="bg-gradient-to-tl from-[#4334cf] to-[#c9f28a] dark:from-[#0083B0] dark:to-[#00B4DB] text-white border-none rounded-md px-4 py-2 font-medium hover:shadow-md transition-all duration-200"
                    href="https://jobless-nabilazizi.netlify.app/"
                    target="_blank"
                  >
                    Demo
                  </a>
                </div>
              </div>
            </div>
            <div className="text-center shadow-lg py-5 lg:max-w-[50%] px-5 rounded-xl my-10 flex-1 dark:bg-[#16161a]">
              <div className="flex justify-center items-center ">
                <Image src={space} width={400} height={300} className="rounded-xl hover:shadow-md hover:scale-105 transition-all duration-200" />
              </div>
              <h3 className="text-lg  font-medium pt-8 pb-2 text-[#4334cf] dark:text-[#00B4DB]">Space Website</h3>
              <p className="lg:text-base text-xs py-2 leading-8 text-gray-800 dark:text-[#94a1b2] ">
                SPACE is an interesting and unique <span className="text-[#4334cf] dark:text-[#00B4DB]">fake project</span> of learning for me as it combines elements of modern design, animation, and aesthetically pleasing layout to create
                a fun and inspiring illustrated learning experience.
              </p>
              <h4 className="pt-4 text-[#4334cf] dark:text-[#00B4DB]">Tools I've Use</h4>
              <p className="text-gray-800 dark:text-[#94a1b2] py-1 font-bold">React.Js</p>
              <p className="text-gray-800 dark:text-[#94a1b2] py-1 font-bold">TailwindCSS</p>
              <div className="flex justify-center items-center gap-8">
                <div className="py-4  hover:scale-105 transition-all duration-200">
                  <a
                    className="bg-gradient-to-tl from-[#4334cf] to-[#c9f28a] dark:from-[#0083B0] dark:to-[#00B4DB] text-white border-none rounded-md px-4 py-2 font-medium hover:shadow-md transition-all duration-200"
                    href="https://github.com/NabilAzizii/Latihan-Frontend/tree/space_website"
                    target="_blank"
                  >
                    Code
                  </a>
                </div>
                <div className="py-4 hover:scale-105 transition-all duration-200">
                  <a
                    className="bg-gradient-to-tl from-[#4334cf] to-[#c9f28a] dark:from-[#0083B0] dark:to-[#00B4DB] text-white border-none rounded-md px-4 py-2 font-medium hover:shadow-md transition-all duration-200"
                    href="https://space-fake-project-nabil-azizi.netlify.app/"
                    target="_blank"
                  >
                    Demo
                  </a>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/*  */}

        <section className=" flex justify-center items-center">
          <div className="container mx-auto px-6 pt-10 pb-6 text-center dark:text-white"> Made by ❤ Muhammad Nabil Azizi</div>
        </section>
      </main>
    </div>
  );
}
